apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: ruby-form
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS contact_app;
    USE contact_app;
    CREATE TABLE IF NOT EXISTS submissions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      email VARCHAR(150) NOT NULL,
      message TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
