apiVersion: v1
kind: Service
metadata:
  name: php-form-app
  namespace: ruby-form
spec:
  type: NodePort
  selector:
    app: php-form-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
