apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ruby-form
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: contact_app
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppassword
